// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF3e6e3l6Yom9MxSb6xWcLntqUFJ-fsEg',
    appId: '1:973146043959:web:19d7d9dff3bc75026cf1b2',
    messagingSenderId: '973146043959',
    projectId: 'praktikum06-f1bd2',
    authDomain: 'praktikum06-f1bd2.firebaseapp.com',
    storageBucket: 'praktikum06-f1bd2.appspot.com',
    measurementId: 'G-9FZH6RRET0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2iQX2gsMWeThDkRlQ8bfc7fEIGV4DrsM',
    appId: '1:973146043959:android:6564cafd100df0746cf1b2',
    messagingSenderId: '973146043959',
    projectId: 'praktikum06-f1bd2',
    storageBucket: 'praktikum06-f1bd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQOIYXvAvAGKt-KygNsCAX413HCkZ1ApA',
    appId: '1:973146043959:ios:65d5306383bbc38b6cf1b2',
    messagingSenderId: '973146043959',
    projectId: 'praktikum06-f1bd2',
    storageBucket: 'praktikum06-f1bd2.appspot.com',
    iosBundleId: 'com.example.praktikum06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQOIYXvAvAGKt-KygNsCAX413HCkZ1ApA',
    appId: '1:973146043959:ios:65d5306383bbc38b6cf1b2',
    messagingSenderId: '973146043959',
    projectId: 'praktikum06-f1bd2',
    storageBucket: 'praktikum06-f1bd2.appspot.com',
    iosBundleId: 'com.example.praktikum06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF3e6e3l6Yom9MxSb6xWcLntqUFJ-fsEg',
    appId: '1:973146043959:web:1eaf59eff480482b6cf1b2',
    messagingSenderId: '973146043959',
    projectId: 'praktikum06-f1bd2',
    authDomain: 'praktikum06-f1bd2.firebaseapp.com',
    storageBucket: 'praktikum06-f1bd2.appspot.com',
    measurementId: 'G-H49C3J2H5G',
  );
}
